development:
  adapter: postgresql
  encoding: unicode
  database: tailor
  host: localhost
  pool: 5
  username: liorlight
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tailor
  host: localhost
  pool: 5
  username: liorlight
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tailor
  host: localhost
  pool: 5
  username: liorlight
  password: